server:
  port: 8080
  servlet:
    contextPath: /admin-api

management:
  server:
    servlet:
      context-path: /manage
    port: -1

logging:
  level:
    root: 'WARN'
    org.springframework.http.client: 'OFF'
    org.springframework.web.client: 'OFF'
    sun.net.www.protocol.http: 'OFF'

stlcourts:
  security:
    jwt:
      tokenExpirationTime: 1 # Number of minutes
      refreshTokenExpTime: 60 # Minutes
      tokenIssuer: http://yourSTLCourts.com
      tokenSigningKey: ${JWT_TOKEN_SIGNING_KEY}

---
spring:
  profiles.active: local
---
spring:
  profiles: local
  allowedOrigin: http://localhost:4200
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: svc.dialects.ImprovedHSQLDialect
  datasource:
    data: classpath*:hsql/*.sql
stlcourts:
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
management:
  server:
    port: 8080
---
spring:
  profiles: localWithHSQLAccess
  allowedOrigin: http://localhost:4200
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: svc.dialects.ImprovedHSQLDialect
  datasource:
    data: classpath*:hsql/*.sql
stlcourts:
  runHeadless: false
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
---
spring:
  profiles: qa
  jpa:
    hibernate:
      ddl-auto: none
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}